Repository MonishRaman/Placify-Smarter_Placements-Sharper_Talent, pull requests merged in 2025-09, with the labels that each got.

#419 Added Router and Update Functionality for jobs
  server/controllers/jobController.js
  server/routes/job.js
  server/server.js
Labels: Level 2, gssoc25

#422 feat: added form for taking interview experience response
  package-lock.json
  package.json
  server/controllers/jobController.js
  src/pages/Student/InterviewExperience.jsx
Labels: Level 1, gssoc25, BONUS 5

#433 Add Responsive Navbar to Role selection Page
  src/pages/RoleSelectionPage.jsx
Labels: Level 2, gssoc25, BONUS 10

#438 Added darkMode support and improved ui of company profile
  server/yarn.lock
  src/pages/company/CompanyProfile.jsx
Labels: Level 3, gssoc25, BONUS 10

#449 Refactor: Remove Code Duplication in Authentication Controller
  server/controllers/authController.js
Labels: Level 2, gssoc25, BONUS 10

#452 feat(server): add aptitude question api
  server/controllers/questionController.js
  server/models/Question.js
  server/routes/questions.js
  server/server.js
  server/yarn.lock
Labels: Level 3, gssoc25, BONUS 10

#454 feat(questions): add generate question endpoint
  server/controllers/questionsController.js
  server/models/Question.js
  server/routes/questions.js
  server/services/ai/gemini.js
  server/services/ai/geminiService.js
Labels: Level 3, gssoc25, BONUS 10

#455 Added delete Job and Apply Job endpoint
  server/controllers/jobController.js
  server/routes/job.js
Labels: Level 3, gssoc25, BONUS 10

#460 Added withdraw application and applied jobs endpoints
  server/controllers/jobController.js
  server/routes/job.js
Labels: Level 3, gssoc25, BONUS 10

#461 (feat): added backend setup for chatbot
  server/controllers/chatController.js
  server/routes/chat.js
  server/server.js
  server/services/ai/gemini.js
  server/services/ai/geminiService.js
Labels: Level 3, gssoc25, BONUS 10

#462 feat: added backend integration in aptitute component
  src/components/AptitudePreparation.jsx
Labels: Level 3, gssoc25, BONUS 10

#468 Optimize Resume Score Controller for Performance & Maintainability
  server/controllers/resumeScoreController.js
Labels: Level 3, gssoc25, BONUS 10

#472 Integrate Interview Experience Backend with Frontend & Auto-Approve Submissions
  server/controllers/interviewExperienceController.js
  server/server.js
  src/pages/Student/InterviewExperience.jsx
Labels: Level 3, gssoc25, BONUS 10

#496 Feat(Dashboard): Implement Interactive Notification Panel
  src/pages/Student/Dashboard.jsx
Labels: Level 2, gssoc25, BONUS 10

#506 fix(auth): normalize institution role value
  server/controllers/authController.js
  src/pages/register/InstitutionForm.jsx
Labels: Level 3, gssoc25, BONUS 10

#511 Feature: Backend Integration for Institution Dashboard
  server/yarn.lock
  src/pages/Institution/InstitutionDashboard.jsx
Labels: Level 3, gssoc25, BONUS 10

#522 Added API endpoints for getting Jobs On company portal
  server/controllers/jobController.js
  server/routes/Payment.js
  server/routes/job.js
Labels: Level 3, gssoc25, BONUS 10

#515 Institution Form Input Fields
  src/pages/register/InstitutionForm.jsx
Labels: Level 3, gssoc25, BONUS 10

#509 fix(backend): add required models
  .gitignore
  server/models/CouponModel.js
  server/models/PaymentModel.js
  server/routes/Payment.js
Labels: Level 3, gssoc25

#525 Refactor feedbackController.js for cleaner structure and consistency
  server/controllers/feedbackController.js
Labels: Level 3, gssoc25

#528 Added a EditJob page for Company
  src/App.jsx
  src/pages/company/EditJob.jsx
  src/pages/company/MyCompanyJobs.jsx
Labels: Level 3, gssoc25

#529 Toggle button for cursor added
  src/App.jsx
  src/components/CursorToggle.jsx
  src/components/Header.jsx
  src/context/CursorContext.jsx
  src/layouts/CompanyDashboardLayout.jsx
  src/layouts/DashboardLayout.jsx
  src/layouts/EmployeeDashboardLayout.jsx
  src/layouts/InstitutionDashboardLayout.jsx
  src/pages/LandingPage.jsx
Labels: Level 3, gssoc25

#532 Performance Overview Dashboard
  server/controllers/authController.js
  src/pages/employee/PerformanceOverview.jsx
  src/pages/employee/SkillDevelopmentTracker.jsx
Labels: Level 3, gssoc25

#533 Learning Resources Hub - Employee Learning Platform
  src/pages/employee/LearningResources.jsx
Labels: Level 3, gssoc25

#539 Add Career Progression Feature
  src/pages/employee/CareerProgression.jsx
Labels: Level 3, gssoc25

#541 Improved CompanyJobs Page and added Filters
  src/App.jsx
  src/pages/company/MyCompanyJobs.jsx
Labels: Level 3, gssoc25

#542 Refactor ContactPage: reorder imports and replace Twitter icon with SVG
  src/pages/ContactPage.jsx
Labels: Level 3, gssoc25

#544 Refactor form components to include unique IDs for inputs and improve password validation logic
  src/components/FormInput.jsx
  src/pages/register/CompanyForm.jsx
  src/pages/register/EmployeeForm.jsx
  src/pages/register/InstitutionForm.jsx
  src/pages/register/StudentForm.jsx
Labels: Level 3, gssoc25

#548 Integrated backend to update and delete Job
  server/models/CouponModel.js
  server/models/PaymentModel.js
  src/pages/company/EditJob.jsx
Labels: Level 3, gssoc25

#564 Add z-index to icons in AuthPage for improved layering
  src/pages/AuthPage.jsx
Labels: Level 3, gssoc25

#577 Improved Company Side Bar Behaviour
  src/components/CompanySidebar.jsx
Labels: Level 3, gssoc25

#579 improved Company Profile and Reduced ApiCalls
  server/uploads/1758727240592-300459590.webp
  server/uploads/1758727788432-137005535.webp
  src/layouts/CompanyDashboardLayout.jsx
  src/pages/company/CompanyDashboard.jsx
  src/pages/company/CompanyProfile.jsx
Labels: Level 3, gssoc25

#581 Improved The ui of editjobpage And added Alert
  package-lock.json
  package.json
  src/pages/company/EditJob.jsx
Labels: Level 3, gssoc25

#583 feat: Implement Backend Dry-Run for Python Code
  server/controllers/dryRunController.js
  server/routes/dryrun.js
Labels: Level 3, gssoc25

#584 feat: Implement Backend Dry-Run for Java Code
  server/controllers/javaDryRunController.js
  server/routes/javaDryRun.js
Labels: Level 3, gssoc25

#585 feat: Implement Backend Dry-Run for C-Cpp
  server/controllers/cDryRunController.js
  server/routes/cDryRun.js
  server/routes/dryrun.js
  server/server.js
Labels: Level 3, gssoc25

#603 Fix login form validation
  src/pages/AuthPage.jsx
  src/pages/ContactPage.jsx
  src/pages/company/EditJob.jsx
Labels: Level 3, gssoc25

#602 feat: Company sidebar refractored
  src/components/CompanySidebar.jsx
Labels: Level 3, gssoc25

#600 feat: Fix Company logic
  server/controllers/authController.js
  src/pages/register/CompanyForm.jsx
Labels: Level 3, gssoc25

#614 Fix: Scroll to top when any page loads
  src/pages/register/CompanyForm.jsx
  src/pages/register/EmployeeForm.jsx
  src/pages/register/InstitutionForm.jsx
  src/pages/register/StudentForm.jsx
Labels: Level 3, gssoc25
