Repository MonishRaman/Placify-Smarter_Placements-Sharper_Talent, pull requests merged in 2025-08, with the labels that each got.

#229 Settings page
  src/pages/Institution/Settings.jsx
Labels: Component, Level 2, gssoc25, UI, animation, database, Navigation

#237 Add Real-Time Speech-to-Text Integration for Mock Interview
  src/components/InterviewLeft.jsx
  src/components/InterviewRight.jsx
  src/pages/Student/InterviewInterface.jsx
Labels: Level 3, gssoc25, AI

#239 Add Contact Page with Google Form Integration
  src/App.jsx
  src/pages/ContactPage.jsx
  src/pages/RoleSelectionPage.jsx
Labels: Level 2, gssoc25, authentication, data

#245 fix(ui): adjust scroll-to-top button position to prevent overlap
  src/App.jsx
  src/components/Footer.jsx
Labels: Level 2, gssoc25

#257 Fix/256-footer-links-updated
  src/components/Footer.jsx
Labels: Level 1, gssoc25

#259 Added animation to comapny form using framer motion and updated the forminput to support diffrent colour themes
  src/components/FormInput.jsx
  src/pages/register/CompanyForm.jsx
Labels: Level 1, gssoc25

#264 Improved the Institution register Page and adding animation using fra…
  src/pages/register/InstitutionForm.jsx
Labels: Level 1, gssoc25

#269 Enhance Overall Homepage with Gradients, Theme-Based Colors, and Vibrant UI Effects
  src/index.css
  src/pages/LandingPage.jsx
Labels: Level 2, gssoc25

#270 Enhance Footer with Gradient Background & Subtle Border Styling
  src/components/Footer.jsx
Labels: Level 1, gssoc25

#272 issue create automate message added
  .github/workflows/issue-create-automate-message.yml
Labels: gssoc25

#280 pr create automate message added
  .github/workflows/pr-create-automate-message.yml
Labels: Level 2, gssoc25

#282 Implement dynamic year in footer.jsx
  src/components/Footer.jsx
Labels: Level 1, gssoc25

#286 added dark theme support to aptitude page and designed the page
  src/pages/Student/Aptitude.jsx
Labels: Level 3, gssoc25

#288 Added a resume builder
  src/App.jsx
  src/pages/LandingPage.jsx
  src/pages/Resume.jsx
Labels: Level 3, gssoc25, AI

#289 Added dark theme support to the resume builderpage and improved ui
  src/pages/Student/ResumeBuilder.jsx
Labels: Level 1, gssoc25

#313 Issue #211 Resolved – User Profile System & UI Fixes
  index.html
  package-lock.json
  package.json
  server/controllers/authController.js
  server/models/Student.js
  server/models/User.js
  server/package-lock.json
  server/package.json
  server/uploads/1755412942610-800575999.jpg
  src/App.jsx
  src/api/api.js
  src/components/Chatbot.jsx
  src/components/FormInput.jsx
  src/components/Header.jsx
  src/components/RegistrationHeader.jsx
  src/components/ThemeToggle.jsx
  src/pages/LandingPage.jsx
  src/pages/ProfilePage.jsx
  src/pages/RoleSelectionPage.jsx
  src/pages/Student/Aptitude.jsx
  src/pages/Student/Coding.jsx
  src/pages/Student/Dashboard.jsx
  src/pages/Student/InterviewInterface.jsx
  src/pages/Student/Jobs.jsx
  src/pages/Student/ResumeBuilder.jsx
  src/pages/Student/UserJobs.jsx
  src/pages/register/CompanyForm.jsx
  src/pages/register/EmployeeForm.jsx
  src/pages/register/InstitutionForm.jsx
  src/pages/register/StudentForm.jsx
Labels: Level 3, gssoc25

#325 Added register button
  src/pages/RoleSelectionPage.jsx
Labels: Level 1, gssoc25

#326 Added Footer to different pages
  src/pages/RoleSelectionPage.jsx
  src/pages/register/CompanyForm.jsx
  src/pages/register/EmployeeForm.jsx
  src/pages/register/InstitutionForm.jsx
  src/pages/register/StudentForm.jsx
Labels: Level 2, gssoc25

#345 [FEAT] : Add Snake Trail Cursor Effect
  server/yarn.lock
  src/App.jsx
  src/components/CursorTrail.jsx
Labels: Level 2, gssoc25

#346 Feat(ml) create unified analysis report generator
  ml_modules/INTEGRATION_GUIDE.md
  ml_modules/README.md
  ml_modules/integration_example.py
  ml_modules/main_analyzer.py
  ml_modules/requirements.txt.txt
  ml_modules/test_analyzer.py
Labels: Level 2, gssoc25

#348 Add Job Posting Form with UI Consistency and Dark Mode Support
  src/pages/company/postJob.jsx
Labels: Level 2, gssoc25

#351 fixed missing routing in role selection cards
  src/pages/RoleSelectionPage.jsx
Labels: Level 2, gssoc25

#360 Fixed theme issues
  index.html
  src/pages/ProfilePage.jsx
  src/pages/Student/Dashboard.jsx
  src/utils/theme.js
Labels: Level 2, gssoc25

#361 Refractored and implemented robust resume builder system
  package-lock.json
  package.json
  src/App.jsx
  src/components/ResumeBuilder/EducationForm.jsx
  src/components/ResumeBuilder/ExperienceForm.jsx
  src/components/ResumeBuilder/PersonalInfoForm.jsx
  src/components/ResumeBuilder/ProjectsForm.jsx
  src/components/ResumeBuilder/ResumePreview.jsx
  src/components/ResumeBuilder/SkillsForm.jsx
  src/components/ResumeBuilder/index.js
  src/pages/Student/ResumeBuilder.jsx
  src/utils/pdfGenerator.js
  src/utils/resumeValidation.js
Labels: Level 3, gssoc25

#362 Backend Implementation for Resume Builder
  server/controllers/resumeController.js
  server/models/Resume.js
  server/models/User.js
  server/routes/resume.js
  server/server.js
Labels: Level 3, gssoc25

#370 Implemented the integration of frontend and backend of resume builder
  src/api/resumeApi.js
  src/pages/Student/ResumeBuilder.jsx
Labels: Level 3, gssoc25

#371 Added collaboration section in Company section
  src/components/CompanyCollaboration/CardGrid.jsx
  src/components/CompanyCollaboration/SectionWrapper.jsx
  src/pages/company/Collaboration.jsx
Labels: Level 1, gssoc25

#373 fixed go to dashboard button taking to register page issue
  src/pages/LandingPage.jsx
Labels: Level 1, gssoc25

#385 add standard password policy checklist across forms
  src/pages/register/CompanyForm.jsx
  src/pages/register/EmployeeForm.jsx
  src/pages/register/InstitutionForm.jsx
  src/pages/register/StudentForm.jsx
Labels: Level 2, gssoc25

#388 feat: Enhance Keyword Checker with Strict Matching Mode
  ml_modules/answer_accuracy/keyword_checker.py
  ml_modules/answer_accuracy/test_keyword_checker.py
Labels: Level 2, gssoc25

#389 ATS Score Integration with Frontend
  server/controllers/atsController.js
  server/controllers/resumeScoreController.js
  src/pages/Student/ResumeATS.jsx
Labels: Level 3, gssoc25

#386 Fix: Prevent copy/paste in password fields
  src/components/FormInput.jsx
  src/pages/register/CompanyForm.jsx
  src/pages/register/EmployeeForm.jsx
  src/pages/register/InstitutionForm.jsx
  src/pages/register/StudentForm.jsx
Labels: Level 1, gssoc25

#394 fix back to top button
  src/components/Footer.jsx
Labels: good first issue, Level 2, gssoc25

#400 Add Newsletter Subscription with Toast Notifications
  src/components/Footer.jsx
Labels: Level 2, gssoc25

#406 Refactored schema and maitained consistency
  server/models/User.js
Labels: Level 2, gssoc25

#410 Fixed the alignment issue in footer component
  package-lock.json
  package.json
  server/services/ats/atsScorer.js
  src/components/Footer.jsx
Labels: Level 2, gssoc25

#411 fixed the ui breakage in chatbot component
  src/components/Chatbot.jsx
  src/components/Footer.jsx
Labels: Level 2, gssoc25

#412 Enhance Keyword Checker with Fuzzy String Matching
  ml_modules/answer_accuracy/FUZZY_MATCHING_README.md
  ml_modules/answer_accuracy/keyword_checker.py
  ml_modules/answer_accuracy/test_fuzzy_keyword_checker.py
  ml_modules/requirements.txt
Labels: Level 2, gssoc25
